"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r-iv&ksfr*427&f&&)5o^x0l$mh4%#)ljh(&(+jn-o71+0(wsa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # เพิ่มบรรทัดนี้
    'sheets_service', 
    'rest_framework.authtoken', # <--- ต้องมีบรรทัดนี้

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# กำหนดค่า REST_FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # ใช้ Custom Authentication Class ที่เราจะสร้างขึ้น (ในขั้นตอนที่ 3)
        # 'sheets_service.authentication.ExpiringTokenAuthentication' # ชื่อเต็มของคลาสและไฟล์
        'sheets_service.authentication.ExpiringTokenAuthentication', # สมมติว่าไฟล์ชื่อ authentication.py
        'rest_framework.authentication.SessionAuthentication', # อาจจะยังคง Session Auth ไว้ก็ได้
        'rest_framework.authentication.BasicAuthentication', # อาจจะยังคง Basic Auth ไว้ก็ได้
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # ตัวอย่าง: กำหนด default ให้ต้องล็อกอิน
    ],
    # ... การตั้งค่าอื่นๆ ของ DRF ...
}

# กำหนดให้ DRF ใช้ Model Token ที่เราสร้างขึ้นเอง
# ชื่อ 'sheets_service.ExpiringToken' คือ <ชื่อ app>.<ชื่อ Model>
AUTH_TOKEN_MODEL = 'sheets_service.ExpiringToken'

# กำหนดระยะเวลาหมดอายุของ Token (เป็นวินาที)
# ตัวอย่าง: หมดอายุใน 24 ชั่วโมง (24 * 60 * 60 = 86400 วินาที)
# TOKEN_EXPIRY_TIME = 86400 # กำหนดค่านี้ขึ้นมาเอง ใช้ชื่ออะไรก็ได้ที่คุณเข้าใจ
TOKEN_EXPIRY_TIME = 86400 # กำหนดค่านี้ขึ้นมาเอง ใช้ชื่ออะไรก็ได้ที่คุณเข้าใจ