# Generated by Django 5.0.4 on 2025-05-09 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_service', '0001_initial'),
        ('subject_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='sheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_service.subject'),
        ),
    ]
