# Generated by Django 5.0.4 on 2025-05-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_service', '0002_rename_title_sheet_name_alter_sheet_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sheet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet_service.subject'),
        ),
    ]
