# Generated by Django 5.0.4 on 2025-05-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_service', '0003_subject_sheet_price_alter_sheet_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='price',
        ),
    ]
