# Generated by Django 5.2.1 on 2025-05-11 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_service', '0004_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='subject_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
