# Generated by Django 5.2.1 on 2025-05-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_service', '0005_sheet_create_date_sheet_image_sheet_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='content',
            new_name='description',
        ),
    ]
