# Generated by Django 5.2.1 on 2025-05-11 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_service', '0006_rename_content_sheet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
